-- ============================================================
-- Flowable 6.8.0 达梦(DM)数据库建表脚本
-- 基于 Flowable Oracle SQL 适配，版本: 6.8.0.0
-- 适配说明: NVARCHAR2, NUMBER, TIMESTAMP, SEQUENCE 均为 Oracle 语法
--           达梦数据库兼容 Oracle 语法，可直接使用
-- ============================================================

SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF6';

-- ============================================================
-- 第1部分: Common 模块 (ACT_GE_PROPERTY, ACT_GE_BYTEARRAY)
-- ============================================================

CREATE TABLE ACT_GE_PROPERTY (
    NAME_ NVARCHAR2(64),
    VALUE_ NVARCHAR2(300),
    REV_ INTEGER,
    PRIMARY KEY (NAME_)
);

CREATE TABLE ACT_GE_BYTEARRAY (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    DEPLOYMENT_ID_ NVARCHAR2(64),
    BYTES_ BLOB,
    GENERATED_ NUMBER(1,0) CHECK (GENERATED_ IN (1,0)),
    PRIMARY KEY (ID_)
);

INSERT INTO ACT_GE_PROPERTY VALUES ('common.schema.version', '6.8.0.0', 1);
INSERT INTO ACT_GE_PROPERTY VALUES ('next.dbid', '1', 1);

-- ============================================================
-- 第2部分: Engine 模块 - 流程定义/部署/运行时表
-- ============================================================

CREATE TABLE ACT_RE_DEPLOYMENT (
    ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255),
    CATEGORY_ NVARCHAR2(255),
    KEY_ NVARCHAR2(255),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    DEPLOY_TIME_ TIMESTAMP(6),
    DERIVED_FROM_ NVARCHAR2(64),
    DERIVED_FROM_ROOT_ NVARCHAR2(64),
    PARENT_DEPLOYMENT_ID_ NVARCHAR2(255),
    ENGINE_VERSION_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RE_MODEL (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    KEY_ NVARCHAR2(255),
    CATEGORY_ NVARCHAR2(255),
    CREATE_TIME_ TIMESTAMP(6),
    LAST_UPDATE_TIME_ TIMESTAMP(6),
    VERSION_ INTEGER,
    META_INFO_ NVARCHAR2(2000),
    DEPLOYMENT_ID_ NVARCHAR2(64),
    EDITOR_SOURCE_VALUE_ID_ NVARCHAR2(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_ NVARCHAR2(64),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RE_PROCDEF (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    NAME_ NVARCHAR2(255),
    KEY_ NVARCHAR2(255) NOT NULL,
    VERSION_ INTEGER NOT NULL,
    DEPLOYMENT_ID_ NVARCHAR2(64),
    RESOURCE_NAME_ NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ NVARCHAR2(4000),
    DESCRIPTION_ NVARCHAR2(2000),
    HAS_START_FORM_KEY_ NUMBER(1,0) CHECK (HAS_START_FORM_KEY_ IN (1,0)),
    HAS_GRAPHICAL_NOTATION_ NUMBER(1,0) CHECK (HAS_GRAPHICAL_NOTATION_ IN (1,0)),
    SUSPENSION_STATE_ INTEGER,
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    DERIVED_FROM_ NVARCHAR2(64),
    DERIVED_FROM_ROOT_ NVARCHAR2(64),
    DERIVED_VERSION_ INTEGER DEFAULT 0 NOT NULL,
    ENGINE_VERSION_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_EXECUTION (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    PROC_INST_ID_ NVARCHAR2(64),
    BUSINESS_KEY_ NVARCHAR2(255),
    PARENT_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    SUPER_EXEC_ NVARCHAR2(64),
    ROOT_PROC_INST_ID_ NVARCHAR2(64),
    ACT_ID_ NVARCHAR2(255),
    IS_ACTIVE_ NUMBER(1,0) CHECK (IS_ACTIVE_ IN (1,0)),
    IS_CONCURRENT_ NUMBER(1,0) CHECK (IS_CONCURRENT_ IN (1,0)),
    IS_SCOPE_ NUMBER(1,0) CHECK (IS_SCOPE_ IN (1,0)),
    IS_EVENT_SCOPE_ NUMBER(1,0) CHECK (IS_EVENT_SCOPE_ IN (1,0)),
    IS_MI_ROOT_ NUMBER(1,0) CHECK (IS_MI_ROOT_ IN (1,0)),
    SUSPENSION_STATE_ INTEGER,
    CACHED_ENT_STATE_ INTEGER,
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    NAME_ NVARCHAR2(255),
    START_ACT_ID_ NVARCHAR2(255),
    START_TIME_ TIMESTAMP(6),
    START_USER_ID_ NVARCHAR2(255),
    LOCK_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    IS_COUNT_ENABLED_ NUMBER(1,0) CHECK (IS_COUNT_ENABLED_ IN (1,0)),
    EVT_SUBSCR_COUNT_ INTEGER,
    TASK_COUNT_ INTEGER,
    JOB_COUNT_ INTEGER,
    TIMER_JOB_COUNT_ INTEGER,
    SUSP_JOB_COUNT_ INTEGER,
    DEADLETTER_JOB_COUNT_ INTEGER,
    EXTERNAL_WORKER_JOB_COUNT_ INTEGER,
    VAR_COUNT_ INTEGER,
    ID_LINK_COUNT_ INTEGER,
    CALLBACK_ID_ NVARCHAR2(255),
    CALLBACK_TYPE_ NVARCHAR2(255),
    REFERENCE_ID_ NVARCHAR2(255),
    REFERENCE_TYPE_ NVARCHAR2(255),
    PROPAGATED_STAGE_INST_ID_ NVARCHAR2(255),
    BUSINESS_STATUS_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_ACTINST (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER DEFAULT 1,
    PROC_DEF_ID_ NVARCHAR2(64) NOT NULL,
    PROC_INST_ID_ NVARCHAR2(64) NOT NULL,
    EXECUTION_ID_ NVARCHAR2(64) NOT NULL,
    ACT_ID_ NVARCHAR2(255) NOT NULL,
    TASK_ID_ NVARCHAR2(64),
    CALL_PROC_INST_ID_ NVARCHAR2(64),
    ACT_NAME_ NVARCHAR2(255),
    ACT_TYPE_ NVARCHAR2(255) NOT NULL,
    ASSIGNEE_ NVARCHAR2(255),
    START_TIME_ TIMESTAMP(6) NOT NULL,
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    TRANSACTION_ORDER_ INTEGER,
    DELETE_REASON_ NVARCHAR2(2000),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_EVT_LOG (
    LOG_NR_ NUMBER(19),
    TYPE_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    TIME_STAMP_ TIMESTAMP(6) NOT NULL,
    USER_ID_ NVARCHAR2(255),
    DATA_ BLOB,
    LOCK_OWNER_ NVARCHAR2(255),
    LOCK_TIME_ TIMESTAMP(6),
    IS_PROCESSED_ NUMBER(3) DEFAULT 0,
    PRIMARY KEY (LOG_NR_)
);

CREATE SEQUENCE ACT_EVT_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ACT_PROCDEF_INFO (
    ID_ NVARCHAR2(64) NOT NULL,
    PROC_DEF_ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    INFO_JSON_ID_ NVARCHAR2(64),
    PRIMARY KEY (ID_)
);

-- Engine indexes
CREATE INDEX ACT_IDX_EXEC_BUSKEY ON ACT_RU_EXECUTION(BUSINESS_KEY_);
CREATE INDEX ACT_IDX_EXEC_ROOT ON ACT_RU_EXECUTION(ROOT_PROC_INST_ID_);
CREATE INDEX ACT_IDX_EXEC_REF_ID_ ON ACT_RU_EXECUTION(REFERENCE_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_START ON ACT_RU_ACTINST(START_TIME_);
CREATE INDEX ACT_IDX_RU_ACTI_END ON ACT_RU_ACTINST(END_TIME_);
CREATE INDEX ACT_IDX_RU_ACTI_PROC ON ACT_RU_ACTINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_PROC_ACT ON ACT_RU_ACTINST(PROC_INST_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_EXEC ON ACT_RU_ACTINST(EXECUTION_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_EXEC_ACT ON ACT_RU_ACTINST(EXECUTION_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_TASK ON ACT_RU_ACTINST(TASK_ID_);

INSERT INTO ACT_GE_PROPERTY VALUES ('schema.version', '6.8.0.0', 1);
INSERT INTO ACT_GE_PROPERTY VALUES ('schema.history', 'create(6.8.0.0)', 1);

-- ============================================================
-- 第3部分: Task 模块 (ACT_RU_TASK, ACT_HI_TASKINST, ACT_HI_TSK_LOG)
-- ============================================================

CREATE TABLE ACT_RU_TASK (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    TASK_DEF_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PROPAGATED_STAGE_INST_ID_ NVARCHAR2(255),
    NAME_ NVARCHAR2(255),
    PARENT_TASK_ID_ NVARCHAR2(64),
    DESCRIPTION_ NVARCHAR2(2000),
    TASK_DEF_KEY_ NVARCHAR2(255),
    OWNER_ NVARCHAR2(255),
    ASSIGNEE_ NVARCHAR2(255),
    DELEGATION_ NVARCHAR2(64),
    PRIORITY_ INTEGER,
    CREATE_TIME_ TIMESTAMP(6),
    DUE_DATE_ TIMESTAMP(6),
    CATEGORY_ NVARCHAR2(255),
    SUSPENSION_STATE_ INTEGER,
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    FORM_KEY_ NVARCHAR2(255),
    CLAIM_TIME_ TIMESTAMP(6),
    IS_COUNT_ENABLED_ NUMBER(1,0) CHECK (IS_COUNT_ENABLED_ IN (1,0)),
    VAR_COUNT_ INTEGER,
    ID_LINK_COUNT_ INTEGER,
    SUB_TASK_COUNT_ INTEGER,
    PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_TASK_CREATE ON ACT_RU_TASK(CREATE_TIME_);
CREATE INDEX ACT_IDX_TASK_SCOPE ON ACT_RU_TASK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SUB_SCOPE ON ACT_RU_TASK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SCOPE_DEF ON ACT_RU_TASK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

INSERT INTO ACT_GE_PROPERTY VALUES ('task.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第4部分: IdentityLink 模块 (ACT_RU_IDENTITYLINK)
-- ============================================================

CREATE TABLE ACT_RU_IDENTITYLINK (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    GROUP_ID_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255),
    USER_ID_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_IDENT_LNK_USER ON ACT_RU_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_GROUP ON ACT_RU_IDENTITYLINK(GROUP_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE ON ACT_RU_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SUB_SCOPE ON ACT_RU_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE_DEF ON ACT_RU_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

INSERT INTO ACT_GE_PROPERTY VALUES ('identitylink.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第5部分: Variable 模块 (ACT_RU_VARIABLE)
-- ============================================================

CREATE TABLE ACT_RU_VARIABLE (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ NVARCHAR2(255) NOT NULL,
    NAME_ NVARCHAR2(255) NOT NULL,
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    BYTEARRAY_ID_ NVARCHAR2(64),
    DOUBLE_ NUMBER(*,10),
    LONG_ NUMBER(19,0),
    TEXT_ NVARCHAR2(2000),
    TEXT2_ NVARCHAR2(2000),
    PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_RU_VAR_SCOPE_ID_TYPE ON ACT_RU_VARIABLE(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_RU_VAR_SUB_ID_TYPE ON ACT_RU_VARIABLE(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_VARIABLE_TASK_ID ON ACT_RU_VARIABLE(TASK_ID_);
CREATE INDEX ACT_IDX_VAR_BYTEARRAY ON ACT_RU_VARIABLE(BYTEARRAY_ID_);

INSERT INTO ACT_GE_PROPERTY VALUES ('variable.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第6部分: Job 模块 (ACT_RU_JOB, ACT_RU_TIMER_JOB 等)
-- ============================================================

CREATE TABLE ACT_RU_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    ELEMENT_ID_ NVARCHAR2(255),
    ELEMENT_NAME_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    CORRELATION_ID_ NVARCHAR2(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_TIMER_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    ELEMENT_ID_ NVARCHAR2(255),
    ELEMENT_NAME_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    CORRELATION_ID_ NVARCHAR2(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_SUSPENDED_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255) NOT NULL,
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    ELEMENT_ID_ NVARCHAR2(255),
    ELEMENT_NAME_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    CORRELATION_ID_ NVARCHAR2(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_DEADLETTER_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255) NOT NULL,
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    ELEMENT_ID_ NVARCHAR2(255),
    ELEMENT_NAME_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    CORRELATION_ID_ NVARCHAR2(255),
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_HISTORY_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    LOCK_EXP_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    ADV_HANDLER_CFG_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    SCOPE_TYPE_ NVARCHAR2(255),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_RU_EXTERNAL_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    ELEMENT_ID_ NVARCHAR2(255),
    ELEMENT_NAME_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    CORRELATION_ID_ NVARCHAR2(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    CUSTOM_VALUES_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

-- Job indexes
CREATE INDEX ACT_IDX_JOB_EXCEPTION ON ACT_RU_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_JOB_CUSTOM_VAL_ID ON ACT_RU_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_JOB_CORRELATION_ID ON ACT_RU_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_JOB_SCOPE ON ACT_RU_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SUB_SCOPE ON ACT_RU_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SCOPE_DEF ON ACT_RU_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_TJOB_EXCEPTION ON ACT_RU_TIMER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_TJOB_CUSTOM_VAL_ID ON ACT_RU_TIMER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_TJOB_CORRELATION_ID ON ACT_RU_TIMER_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_TJOB_DUEDATE ON ACT_RU_TIMER_JOB(DUEDATE_);
CREATE INDEX ACT_IDX_TJOB_SCOPE ON ACT_RU_TIMER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SUB_SCOPE ON ACT_RU_TIMER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SCOPE_DEF ON ACT_RU_TIMER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_SJOB_EXCEPTION ON ACT_RU_SUSPENDED_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_SJOB_CUSTOM_VAL_ID ON ACT_RU_SUSPENDED_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_SJOB_CORRELATION_ID ON ACT_RU_SUSPENDED_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_SJOB_SCOPE ON ACT_RU_SUSPENDED_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SUB_SCOPE ON ACT_RU_SUSPENDED_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SCOPE_DEF ON ACT_RU_SUSPENDED_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_DJOB_EXCEPTION ON ACT_RU_DEADLETTER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_DJOB_CUSTOM_VAL_ID ON ACT_RU_DEADLETTER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_DJOB_CORRELATION_ID ON ACT_RU_DEADLETTER_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_DJOB_SCOPE ON ACT_RU_DEADLETTER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SUB_SCOPE ON ACT_RU_DEADLETTER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SCOPE_DEF ON ACT_RU_DEADLETTER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_EJOB_EXCEPTION ON ACT_RU_EXTERNAL_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_EJOB_CUSTOM_VAL_ID ON ACT_RU_EXTERNAL_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_EJOB_CORRELATION_ID ON ACT_RU_EXTERNAL_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_EJOB_SCOPE ON ACT_RU_EXTERNAL_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SUB_SCOPE ON ACT_RU_EXTERNAL_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SCOPE_DEF ON ACT_RU_EXTERNAL_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

INSERT INTO ACT_GE_PROPERTY VALUES ('job.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第7部分: Event Subscription 模块 (ACT_RU_EVENT_SUBSCR)
-- ============================================================

CREATE TABLE ACT_RU_EVENT_SUBSCR (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    EVENT_TYPE_ NVARCHAR2(255) NOT NULL,
    EVENT_NAME_ NVARCHAR2(255),
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    ACTIVITY_ID_ NVARCHAR2(64),
    CONFIGURATION_ NVARCHAR2(255),
    CREATED_ TIMESTAMP(6) NOT NULL,
    PROC_DEF_ID_ NVARCHAR2(64),
    SUB_SCOPE_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(64),
    SCOPE_DEFINITION_ID_ NVARCHAR2(64),
    SCOPE_TYPE_ NVARCHAR2(64),
    LOCK_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_EVENT_SUBSCR_CONFIG_ ON ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR ON ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR_SCOPEREF_ ON ACT_RU_EVENT_SUBSCR(SCOPE_ID_, SCOPE_TYPE_);

INSERT INTO ACT_GE_PROPERTY VALUES ('eventsubscription.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第8部分: EntityLink 模块 (ACT_RU_ENTITYLINK)
-- ============================================================

CREATE TABLE ACT_RU_ENTITYLINK (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    CREATE_TIME_ TIMESTAMP(6),
    LINK_TYPE_ NVARCHAR2(255),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PARENT_ELEMENT_ID_ NVARCHAR2(255),
    REF_SCOPE_ID_ NVARCHAR2(255),
    REF_SCOPE_TYPE_ NVARCHAR2(255),
    REF_SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    ROOT_SCOPE_ID_ NVARCHAR2(255),
    ROOT_SCOPE_TYPE_ NVARCHAR2(255),
    HIERARCHY_TYPE_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE INDEX ACT_IDX_ENT_LNK_SCOPE ON ACT_RU_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_REF_SCOPE ON ACT_RU_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_ROOT_SCOPE ON ACT_RU_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_SCOPE_DEF ON ACT_RU_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

INSERT INTO ACT_GE_PROPERTY VALUES ('entitylink.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第9部分: Batch 模块 (FLW_RU_BATCH)
-- ============================================================

CREATE TABLE FLW_RU_BATCH (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ NVARCHAR2(64) NOT NULL,
    SEARCH_KEY_ NVARCHAR2(255),
    SEARCH_KEY2_ NVARCHAR2(255),
    CREATE_TIME_ TIMESTAMP(6) NOT NULL,
    COMPLETE_TIME_ TIMESTAMP(6),
    STATUS_ NVARCHAR2(255),
    BATCH_DOC_ID_ NVARCHAR2(64),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE FLW_RU_BATCH_PART (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    BATCH_ID_ NVARCHAR2(64),
    TYPE_ NVARCHAR2(64) NOT NULL,
    SCOPE_ID_ NVARCHAR2(64),
    SUB_SCOPE_ID_ NVARCHAR2(64),
    SCOPE_TYPE_ NVARCHAR2(64),
    SEARCH_KEY_ NVARCHAR2(255),
    SEARCH_KEY2_ NVARCHAR2(255),
    CREATE_TIME_ TIMESTAMP(6) NOT NULL,
    COMPLETE_TIME_ TIMESTAMP(6),
    STATUS_ NVARCHAR2(255),
    RESULT_DOC_ID_ NVARCHAR2(64),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE INDEX FLW_IDX_BATCH_PART ON FLW_RU_BATCH_PART(BATCH_ID_);

INSERT INTO ACT_GE_PROPERTY VALUES ('batch.schema.version', '6.8.0.0', 1);

-- ============================================================
-- 第10部分: History 模块 - 历史流程实例/任务/变量等
-- ============================================================

CREATE TABLE ACT_HI_PROCINST (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER DEFAULT 1,
    PROC_INST_ID_ NVARCHAR2(64) NOT NULL,
    BUSINESS_KEY_ NVARCHAR2(255),
    PROC_DEF_ID_ NVARCHAR2(64) NOT NULL,
    START_TIME_ TIMESTAMP(6) NOT NULL,
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    START_USER_ID_ NVARCHAR2(255),
    START_ACT_ID_ NVARCHAR2(255),
    END_ACT_ID_ NVARCHAR2(255),
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    DELETE_REASON_ NVARCHAR2(2000),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    NAME_ NVARCHAR2(255),
    CALLBACK_ID_ NVARCHAR2(255),
    CALLBACK_TYPE_ NVARCHAR2(255),
    REFERENCE_ID_ NVARCHAR2(255),
    REFERENCE_TYPE_ NVARCHAR2(255),
    PROPAGATED_STAGE_INST_ID_ NVARCHAR2(255),
    BUSINESS_STATUS_ NVARCHAR2(255),
    PRIMARY KEY (ID_),
    UNIQUE (PROC_INST_ID_)
);

CREATE TABLE ACT_HI_ACTINST (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER DEFAULT 1,
    PROC_DEF_ID_ NVARCHAR2(64) NOT NULL,
    PROC_INST_ID_ NVARCHAR2(64) NOT NULL,
    EXECUTION_ID_ NVARCHAR2(64) NOT NULL,
    ACT_ID_ NVARCHAR2(255) NOT NULL,
    TASK_ID_ NVARCHAR2(64),
    CALL_PROC_INST_ID_ NVARCHAR2(64),
    ACT_NAME_ NVARCHAR2(255),
    ACT_TYPE_ NVARCHAR2(255) NOT NULL,
    ASSIGNEE_ NVARCHAR2(255),
    START_TIME_ TIMESTAMP(6) NOT NULL,
    END_TIME_ TIMESTAMP(6),
    TRANSACTION_ORDER_ INTEGER,
    DURATION_ NUMBER(19,0),
    DELETE_REASON_ NVARCHAR2(2000),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_DETAIL (
    ID_ NVARCHAR2(64) NOT NULL,
    TYPE_ NVARCHAR2(255) NOT NULL,
    PROC_INST_ID_ NVARCHAR2(64),
    EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    ACT_INST_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255) NOT NULL,
    VAR_TYPE_ NVARCHAR2(64),
    REV_ INTEGER,
    TIME_ TIMESTAMP(6) NOT NULL,
    BYTEARRAY_ID_ NVARCHAR2(64),
    DOUBLE_ NUMBER(*,10),
    LONG_ NUMBER(19,0),
    TEXT_ NVARCHAR2(2000),
    TEXT2_ NVARCHAR2(2000),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_COMMENT (
    ID_ NVARCHAR2(64) NOT NULL,
    TYPE_ NVARCHAR2(255),
    TIME_ TIMESTAMP(6) NOT NULL,
    USER_ID_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    ACTION_ NVARCHAR2(255),
    MESSAGE_ NVARCHAR2(2000),
    FULL_MSG_ BLOB,
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_ATTACHMENT (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    USER_ID_ NVARCHAR2(255),
    NAME_ NVARCHAR2(255),
    DESCRIPTION_ NVARCHAR2(2000),
    TYPE_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    URL_ NVARCHAR2(2000),
    CONTENT_ID_ NVARCHAR2(64),
    TIME_ TIMESTAMP(6),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_TASKINST (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER DEFAULT 1,
    PROC_DEF_ID_ NVARCHAR2(64),
    TASK_DEF_ID_ NVARCHAR2(64),
    TASK_DEF_KEY_ NVARCHAR2(255),
    PROC_INST_ID_ NVARCHAR2(64),
    EXECUTION_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PROPAGATED_STAGE_INST_ID_ NVARCHAR2(255),
    PARENT_TASK_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255),
    DESCRIPTION_ NVARCHAR2(2000),
    OWNER_ NVARCHAR2(255),
    ASSIGNEE_ NVARCHAR2(255),
    START_TIME_ TIMESTAMP(6) NOT NULL,
    CLAIM_TIME_ TIMESTAMP(6),
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    DELETE_REASON_ NVARCHAR2(2000),
    PRIORITY_ INTEGER,
    DUE_DATE_ TIMESTAMP(6),
    FORM_KEY_ NVARCHAR2(255),
    CATEGORY_ NVARCHAR2(255),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    LAST_UPDATED_TIME_ TIMESTAMP(6),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_TSK_LOG (
    ID_ NUMBER(19),
    TYPE_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64) NOT NULL,
    TIME_STAMP_ TIMESTAMP(6) NOT NULL,
    USER_ID_ NVARCHAR2(255),
    DATA_ NVARCHAR2(2000),
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE SEQUENCE ACT_HI_TASK_EVT_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ACT_HI_VARINST (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER DEFAULT 1,
    PROC_INST_ID_ NVARCHAR2(64),
    EXECUTION_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255) NOT NULL,
    VAR_TYPE_ NVARCHAR2(100),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    BYTEARRAY_ID_ NVARCHAR2(64),
    DOUBLE_ NUMBER(*,10),
    LONG_ NUMBER(19,0),
    TEXT_ NVARCHAR2(2000),
    TEXT2_ NVARCHAR2(2000),
    CREATE_TIME_ TIMESTAMP(6),
    LAST_UPDATED_TIME_ TIMESTAMP(6),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_IDENTITYLINK (
    ID_ NVARCHAR2(64),
    GROUP_ID_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255),
    USER_ID_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    CREATE_TIME_ TIMESTAMP(6),
    PROC_INST_ID_ NVARCHAR2(64),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_HI_ENTITYLINK (
    ID_ NVARCHAR2(64),
    LINK_TYPE_ NVARCHAR2(255),
    CREATE_TIME_ TIMESTAMP(6),
    SCOPE_ID_ NVARCHAR2(255),
    SUB_SCOPE_ID_ NVARCHAR2(255),
    SCOPE_TYPE_ NVARCHAR2(255),
    SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    PARENT_ELEMENT_ID_ NVARCHAR2(255),
    REF_SCOPE_ID_ NVARCHAR2(255),
    REF_SCOPE_TYPE_ NVARCHAR2(255),
    REF_SCOPE_DEFINITION_ID_ NVARCHAR2(255),
    ROOT_SCOPE_ID_ NVARCHAR2(255),
    ROOT_SCOPE_TYPE_ NVARCHAR2(255),
    HIERARCHY_TYPE_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

-- History indexes
CREATE INDEX ACT_IDX_HI_PRO_INST_END ON ACT_HI_PROCINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_PRO_I_BUSKEY ON ACT_HI_PROCINST(BUSINESS_KEY_);
CREATE INDEX ACT_IDX_HI_PRO_SUPER_PROCINST ON ACT_HI_PROCINST(SUPER_PROCESS_INSTANCE_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_START ON ACT_HI_ACTINST(START_TIME_);
CREATE INDEX ACT_IDX_HI_ACT_INST_END ON ACT_HI_ACTINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_ACT_INST_PROCINST ON ACT_HI_ACTINST(PROC_INST_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_EXEC ON ACT_HI_ACTINST(EXECUTION_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_TASK_INST_PROCINST ON ACT_HI_TASKINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_TASK_SCOPE ON ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SUB_SCOPE ON ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SCOPE_DEF ON ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_DETAIL_PROC_INST ON ACT_HI_DETAIL(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_ACT_INST ON ACT_HI_DETAIL(ACT_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_TIME ON ACT_HI_DETAIL(TIME_);
CREATE INDEX ACT_IDX_HI_DETAIL_NAME ON ACT_HI_DETAIL(NAME_);
CREATE INDEX ACT_IDX_HI_DETAIL_TASK_ID ON ACT_HI_DETAIL(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_PROC_INST ON ACT_HI_VARINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_TASK_ID ON ACT_HI_VARINST(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_EXE ON ACT_HI_VARINST(EXECUTION_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_NAME_TYPE ON ACT_HI_VARINST(NAME_, VAR_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SCOPE_ID_TYPE ON ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SUB_ID_TYPE ON ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_TASK ON ACT_HI_IDENTITYLINK(TASK_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_USER ON ACT_HI_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_PROCINST ON ACT_HI_IDENTITYLINK(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE ON ACT_HI_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SUB_SCOPE ON ACT_HI_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE_DEF ON ACT_HI_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE ON ACT_HI_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_REF_SCOPE ON ACT_HI_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_ROOT_SCOPE ON ACT_HI_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE_DEF ON ACT_HI_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

-- ============================================================
-- 第11部分: IDM 模块 (ACT_ID_* 表)
-- 注意: 此模块已禁用(idm.enabled=false)，但仍需建表以防后续启用
-- ============================================================

CREATE TABLE ACT_ID_PROPERTY (
    NAME_ NVARCHAR2(64),
    VALUE_ NVARCHAR2(300),
    REV_ INTEGER,
    PRIMARY KEY (NAME_)
);

INSERT INTO ACT_ID_PROPERTY VALUES ('schema.version', '6.8.0.0', 1);

CREATE TABLE ACT_ID_BYTEARRAY (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    BYTES_ BLOB,
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_GROUP (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_MEMBERSHIP (
    USER_ID_ NVARCHAR2(64),
    GROUP_ID_ NVARCHAR2(64),
    PRIMARY KEY (USER_ID_, GROUP_ID_)
);

CREATE TABLE ACT_ID_USER (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    FIRST_ NVARCHAR2(255),
    LAST_ NVARCHAR2(255),
    DISPLAY_NAME_ NVARCHAR2(255),
    EMAIL_ NVARCHAR2(255),
    PWD_ NVARCHAR2(255),
    PICTURE_ID_ NVARCHAR2(64),
    TENANT_ID_ NVARCHAR2(255) DEFAULT '',
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_INFO (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    USER_ID_ NVARCHAR2(64),
    TYPE_ NVARCHAR2(64),
    KEY_ NVARCHAR2(255),
    VALUE_ NVARCHAR2(255),
    PASSWORD_ BLOB,
    PARENT_ID_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_TOKEN (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    TOKEN_VALUE_ NVARCHAR2(255),
    TOKEN_DATE_ TIMESTAMP(6),
    IP_ADDRESS_ NVARCHAR2(255),
    USER_AGENT_ NVARCHAR2(255),
    USER_ID_ NVARCHAR2(255),
    TOKEN_DATA_ NVARCHAR2(2000),
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_PRIV (
    ID_ NVARCHAR2(64) NOT NULL,
    NAME_ NVARCHAR2(255) NOT NULL,
    PRIMARY KEY (ID_)
);

CREATE TABLE ACT_ID_PRIV_MAPPING (
    ID_ NVARCHAR2(64) NOT NULL,
    PRIV_ID_ NVARCHAR2(64) NOT NULL,
    USER_ID_ NVARCHAR2(255),
    GROUP_ID_ NVARCHAR2(255),
    PRIMARY KEY (ID_)
);

-- IDM indexes
CREATE INDEX ACT_IDX_MEMB_GROUP ON ACT_ID_MEMBERSHIP(GROUP_ID_);
CREATE INDEX ACT_IDX_MEMB_USER ON ACT_ID_MEMBERSHIP(USER_ID_);
CREATE INDEX ACT_IDX_PRIV_MAPPING ON ACT_ID_PRIV_MAPPING(PRIV_ID_);
CREATE INDEX ACT_IDX_PRIV_USER ON ACT_ID_PRIV_MAPPING(USER_ID_);
CREATE INDEX ACT_IDX_PRIV_GROUP ON ACT_ID_PRIV_MAPPING(GROUP_ID_);

-- ============================================================
-- 第12部分: 外键约束 (按依赖顺序添加)
-- ============================================================

-- Common -> Deployment
CREATE INDEX ACT_IDX_BYTEAR_DEPL ON ACT_GE_BYTEARRAY(DEPLOYMENT_ID_);
ALTER TABLE ACT_GE_BYTEARRAY ADD CONSTRAINT ACT_FK_BYTEARR_DEPL FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES ACT_RE_DEPLOYMENT (ID_);

-- Process Definition unique
ALTER TABLE ACT_RE_PROCDEF ADD CONSTRAINT ACT_UNIQ_PROCDEF UNIQUE (KEY_,VERSION_, DERIVED_VERSION_, TENANT_ID_);

-- Execution FKs
CREATE INDEX ACT_IDX_EXE_PROCINST ON ACT_RU_EXECUTION(PROC_INST_ID_);
ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_EXE_PARENT ON ACT_RU_EXECUTION(PARENT_ID_);
ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PARENT FOREIGN KEY (PARENT_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_EXE_SUPER ON ACT_RU_EXECUTION(SUPER_EXEC_);
ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_SUPER FOREIGN KEY (SUPER_EXEC_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_EXE_PROCDEF ON ACT_RU_EXECUTION(PROC_DEF_ID_);
ALTER TABLE ACT_RU_EXECUTION ADD CONSTRAINT ACT_FK_EXE_PROCDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);

-- Task FKs
CREATE INDEX ACT_IDX_TASK_EXEC ON ACT_RU_TASK(EXECUTION_ID_);
ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_EXE FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_TASK_PROCINST ON ACT_RU_TASK(PROC_INST_ID_);
ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_TASK_PROCDEF ON ACT_RU_TASK(PROC_DEF_ID_);
ALTER TABLE ACT_RU_TASK ADD CONSTRAINT ACT_FK_TASK_PROCDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);

-- IdentityLink FKs
CREATE INDEX ACT_IDX_TSKASS_TASK ON ACT_RU_IDENTITYLINK(TASK_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_TSKASS_TASK FOREIGN KEY (TASK_ID_) REFERENCES ACT_RU_TASK (ID_);
CREATE INDEX ACT_IDX_ATHRZ_PROCEDEF ON ACT_RU_IDENTITYLINK(PROC_DEF_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_ATHRZ_PROCEDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
CREATE INDEX ACT_IDX_IDL_PROCINST ON ACT_RU_IDENTITYLINK(PROC_INST_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK ADD CONSTRAINT ACT_FK_IDL_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION (ID_);

-- Variable FKs
ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY FOREIGN KEY (BYTEARRAY_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
CREATE INDEX ACT_IDX_VAR_EXE ON ACT_RU_VARIABLE(EXECUTION_ID_);
ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_EXE FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_VAR_PROCINST ON ACT_RU_VARIABLE(PROC_INST_ID_);
ALTER TABLE ACT_RU_VARIABLE ADD CONSTRAINT ACT_FK_VAR_PROCINST FOREIGN KEY (PROC_INST_ID_) REFERENCES ACT_RU_EXECUTION(ID_);

-- Job FKs
CREATE INDEX ACT_IDX_JOB_EXECUTION_ID ON ACT_RU_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_EXECUTION FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_JOB_PROC_INST_ID ON ACT_RU_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_PROCESS_INSTANCE FOREIGN KEY (PROCESS_INSTANCE_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_JOB_PROC_DEF_ID ON ACT_RU_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_PROC_DEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
ALTER TABLE ACT_RU_JOB ADD CONSTRAINT ACT_FK_JOB_CUSTOM_VAL FOREIGN KEY (CUSTOM_VALUES_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_TJOB_EXECUTION_ID ON ACT_RU_TIMER_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_TIMER_JOB ADD CONSTRAINT ACT_FK_TJOB_EXECUTION FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_TJOB_PROC_INST_ID ON ACT_RU_TIMER_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_TIMER_JOB ADD CONSTRAINT ACT_FK_TJOB_PROCESS_INSTANCE FOREIGN KEY (PROCESS_INSTANCE_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_TJOB_PROC_DEF_ID ON ACT_RU_TIMER_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_TIMER_JOB ADD CONSTRAINT ACT_FK_TJOB_PROC_DEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
ALTER TABLE ACT_RU_TIMER_JOB ADD CONSTRAINT ACT_FK_TJOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
ALTER TABLE ACT_RU_TIMER_JOB ADD CONSTRAINT ACT_FK_TJOB_CUSTOM_VAL FOREIGN KEY (CUSTOM_VALUES_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_SJOB_EXECUTION_ID ON ACT_RU_SUSPENDED_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_SUSPENDED_JOB ADD CONSTRAINT ACT_FK_SJOB_EXECUTION FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_SJOB_PROC_INST_ID ON ACT_RU_SUSPENDED_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_SUSPENDED_JOB ADD CONSTRAINT ACT_FK_SJOB_PROCESS_INSTANCE FOREIGN KEY (PROCESS_INSTANCE_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_SJOB_PROC_DEF_ID ON ACT_RU_SUSPENDED_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_SUSPENDED_JOB ADD CONSTRAINT ACT_FK_SJOB_PROC_DEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
ALTER TABLE ACT_RU_SUSPENDED_JOB ADD CONSTRAINT ACT_FK_SJOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
ALTER TABLE ACT_RU_SUSPENDED_JOB ADD CONSTRAINT ACT_FK_SJOB_CUSTOM_VAL FOREIGN KEY (CUSTOM_VALUES_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_DJOB_EXECUTION_ID ON ACT_RU_DEADLETTER_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_DEADLETTER_JOB ADD CONSTRAINT ACT_FK_DJOB_EXECUTION FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_DJOB_PROC_INST_ID ON ACT_RU_DEADLETTER_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_DEADLETTER_JOB ADD CONSTRAINT ACT_FK_DJOB_PROCESS_INSTANCE FOREIGN KEY (PROCESS_INSTANCE_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
CREATE INDEX ACT_IDX_DJOB_PROC_DEF_ID ON ACT_RU_DEADLETTER_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_DEADLETTER_JOB ADD CONSTRAINT ACT_FK_DJOB_PROC_DEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
ALTER TABLE ACT_RU_DEADLETTER_JOB ADD CONSTRAINT ACT_FK_DJOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
ALTER TABLE ACT_RU_DEADLETTER_JOB ADD CONSTRAINT ACT_FK_DJOB_CUSTOM_VAL FOREIGN KEY (CUSTOM_VALUES_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_EJOB_EXECUTION_ID ON ACT_RU_EXTERNAL_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_EXTERNAL_JOB ADD CONSTRAINT ACT_FK_EJOB_EXECUTION FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION (ID_);
ALTER TABLE ACT_RU_EXTERNAL_JOB ADD CONSTRAINT ACT_FK_EJOB_EXCEPTION FOREIGN KEY (EXCEPTION_STACK_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
ALTER TABLE ACT_RU_EXTERNAL_JOB ADD CONSTRAINT ACT_FK_EJOB_CUSTOM_VAL FOREIGN KEY (CUSTOM_VALUES_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);

-- Event Subscription FK
ALTER TABLE ACT_RU_EVENT_SUBSCR ADD CONSTRAINT ACT_FK_EVENT_EXEC FOREIGN KEY (EXECUTION_ID_) REFERENCES ACT_RU_EXECUTION(ID_);

-- Model FKs
CREATE INDEX ACT_IDX_MODEL_SOURCE ON ACT_RE_MODEL(EDITOR_SOURCE_VALUE_ID_);
ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_SOURCE FOREIGN KEY (EDITOR_SOURCE_VALUE_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
CREATE INDEX ACT_IDX_MODEL_SOURCE_EXTRA ON ACT_RE_MODEL(EDITOR_SOURCE_EXTRA_VALUE_ID_);
ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_SOURCE_EXTRA FOREIGN KEY (EDITOR_SOURCE_EXTRA_VALUE_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
CREATE INDEX ACT_IDX_MODEL_DEPLOYMENT ON ACT_RE_MODEL(DEPLOYMENT_ID_);
ALTER TABLE ACT_RE_MODEL ADD CONSTRAINT ACT_FK_MODEL_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES ACT_RE_DEPLOYMENT (ID_);

-- ProcDef Info FKs
CREATE INDEX ACT_IDX_PROCDEF_INFO_JSON ON ACT_PROCDEF_INFO(INFO_JSON_ID_);
ALTER TABLE ACT_PROCDEF_INFO ADD CONSTRAINT ACT_FK_INFO_JSON_BA FOREIGN KEY (INFO_JSON_ID_) REFERENCES ACT_GE_BYTEARRAY (ID_);
CREATE INDEX ACT_IDX_PROCDEF_INFO_PROC ON ACT_PROCDEF_INFO(PROC_DEF_ID_);
ALTER TABLE ACT_PROCDEF_INFO ADD CONSTRAINT ACT_FK_INFO_PROCDEF FOREIGN KEY (PROC_DEF_ID_) REFERENCES ACT_RE_PROCDEF (ID_);
ALTER TABLE ACT_PROCDEF_INFO ADD CONSTRAINT ACT_UNIQ_INFO_PROCDEF UNIQUE (PROC_DEF_ID_);

-- Batch FKs
ALTER TABLE FLW_RU_BATCH_PART ADD CONSTRAINT FLW_FK_BATCH_PART_PARENT FOREIGN KEY (BATCH_ID_) REFERENCES FLW_RU_BATCH (ID_);

-- IDM FKs
ALTER TABLE ACT_ID_MEMBERSHIP ADD CONSTRAINT ACT_FK_MEMB_GROUP FOREIGN KEY (GROUP_ID_) REFERENCES ACT_ID_GROUP (ID_);
ALTER TABLE ACT_ID_MEMBERSHIP ADD CONSTRAINT ACT_FK_MEMB_USER FOREIGN KEY (USER_ID_) REFERENCES ACT_ID_USER (ID_);
ALTER TABLE ACT_ID_PRIV_MAPPING ADD CONSTRAINT ACT_FK_PRIV_MAPPING FOREIGN KEY (PRIV_ID_) REFERENCES ACT_ID_PRIV (ID_);
ALTER TABLE ACT_ID_PRIV ADD CONSTRAINT ACT_UNIQ_PRIV_NAME UNIQUE (NAME_);

-- ============================================================
-- 建表完成
-- ============================================================
