-- 查询达梦中表的实际存储名称（是否大写）
SELECT TABLE_NAME, TABLE_TYPE
FROM USER_TABLES
ORDER BY TABLE_NAME;

-- 查这3张表的列信息
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN ('SYSTEM_OAUTH2_ACCESS_TOKEN', 'INFRA_API_ERROR_LOG', 'INFRA_API_ACCESS_LOG')
   OR LOWER(TABLE_NAME) IN ('system_oauth2_access_token', 'infra_api_error_log', 'infra_api_access_log')
ORDER BY TABLE_NAME, COLUMN_ID;

-- 查达梦实例的 CASE_SENSITIVE 参数（需要 DBA 权限）
-- SELECT PARA_VALUE FROM V$PARAMETER WHERE PARA_NAME = 'CASE_SENSITIVE';
