-- ============================================================
-- TCMPM 达梦(DM)数据库补充建表脚本
-- 缺失表: SYSTEM_OAUTH2_ACCESS_TOKEN, INFRA_API_ACCESS_LOG, INFRA_API_ERROR_LOG
-- 适配说明: 达梦默认大写表名，无需引号包裹
-- ============================================================

SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS.FF6';

-- ============================================================
-- 第1部分: SYSTEM_OAUTH2_ACCESS_TOKEN (OAuth2 访问令牌表)
-- ============================================================

CREATE SEQUENCE SYSTEM_OAUTH2_ACCESS_TOKEN_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SYSTEM_OAUTH2_ACCESS_TOKEN (
    ID BIGINT NOT NULL,
    ACCESS_TOKEN NVARCHAR2(512) NOT NULL,
    REFRESH_TOKEN NVARCHAR2(512) NOT NULL,
    USER_ID BIGINT NOT NULL,
    USER_TYPE INTEGER NOT NULL,
    USER_INFO NVARCHAR2(4000),
    CLIENT_ID NVARCHAR2(64) NOT NULL,
    SCOPES NVARCHAR2(4000),
    EXPIRES_TIME TIMESTAMP(6) NOT NULL,
    CREATOR NVARCHAR2(64) DEFAULT '',
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    UPDATER NVARCHAR2(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP(6) NOT NULL,
    DELETED SMALLINT DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_SYSTEM_OAUTH2_ACCESS_TOKEN_ACCESS_TOKEN ON SYSTEM_OAUTH2_ACCESS_TOKEN(ACCESS_TOKEN);
CREATE INDEX IDX_SYSTEM_OAUTH2_ACCESS_TOKEN_REFRESH_TOKEN ON SYSTEM_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN);
CREATE INDEX IDX_SYSTEM_OAUTH2_ACCESS_TOKEN_USER_ID ON SYSTEM_OAUTH2_ACCESS_TOKEN(USER_ID);
CREATE INDEX IDX_SYSTEM_OAUTH2_ACCESS_TOKEN_EXPIRES_TIME ON SYSTEM_OAUTH2_ACCESS_TOKEN(EXPIRES_TIME);

COMMENT ON TABLE SYSTEM_OAUTH2_ACCESS_TOKEN IS 'OAuth2 访问令牌表';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.ID IS '编号';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.ACCESS_TOKEN IS '访问令牌';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.REFRESH_TOKEN IS '刷新令牌';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.USER_ID IS '用户编号';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.USER_TYPE IS '用户类型';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.USER_INFO IS '用户信息(JSON)';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.CLIENT_ID IS '客户端编号';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.SCOPES IS '授权范围(JSON)';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.EXPIRES_TIME IS '过期时间';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.CREATOR IS '创建者';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.UPDATER IS '更新者';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSTEM_OAUTH2_ACCESS_TOKEN.DELETED IS '是否删除';

-- ============================================================
-- 第2部分: INFRA_API_ACCESS_LOG (API 访问日志表)
-- ============================================================

CREATE SEQUENCE INFRA_API_ACCESS_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE INFRA_API_ACCESS_LOG (
    ID BIGINT NOT NULL,
    TRACE_ID NVARCHAR2(64) NOT NULL,
    USER_ID BIGINT NOT NULL,
    USER_TYPE INTEGER NOT NULL,
    APPLICATION_NAME NVARCHAR2(50) NOT NULL,
    REQUEST_METHOD NVARCHAR2(16) NOT NULL,
    REQUEST_URL NVARCHAR2(255) NOT NULL,
    REQUEST_PARAMS NVARCHAR2(8000) NOT NULL,
    RESPONSE_BODY NVARCHAR2(8000) NOT NULL,
    USER_IP NVARCHAR2(50) NOT NULL,
    USER_AGENT NVARCHAR2(512) NOT NULL,
    OPERATE_MODULE NVARCHAR2(50) NOT NULL,
    OPERATE_NAME NVARCHAR2(50) NOT NULL,
    OPERATE_TYPE BIGINT NOT NULL,
    BEGIN_TIME TIMESTAMP(6) NOT NULL,
    END_TIME TIMESTAMP(6) NOT NULL,
    DURATION INTEGER NOT NULL,
    RESULT_CODE INTEGER NOT NULL,
    RESULT_MSG NVARCHAR2(512),
    CREATOR NVARCHAR2(64) DEFAULT '',
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    UPDATER NVARCHAR2(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP(6) NOT NULL,
    DELETED SMALLINT DEFAULT 0 NOT NULL,
    TENANT_ID BIGINT DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_INFRA_API_ACCESS_LOG_TRACE_ID ON INFRA_API_ACCESS_LOG(TRACE_ID);
CREATE INDEX IDX_INFRA_API_ACCESS_LOG_USER_ID ON INFRA_API_ACCESS_LOG(USER_ID);
CREATE INDEX IDX_INFRA_API_ACCESS_LOG_CREATE_TIME ON INFRA_API_ACCESS_LOG(CREATE_TIME);

COMMENT ON TABLE INFRA_API_ACCESS_LOG IS 'API 访问日志表';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.ID IS '编号';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.TRACE_ID IS '链路追踪编号';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.USER_ID IS '用户编号';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.USER_TYPE IS '用户类型';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.APPLICATION_NAME IS '应用名';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.REQUEST_METHOD IS '请求方法名';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.REQUEST_URL IS '访问地址';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.REQUEST_PARAMS IS '请求参数';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.RESPONSE_BODY IS '响应结果';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.USER_IP IS '用户 IP';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.USER_AGENT IS '浏览器 UA';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.OPERATE_MODULE IS '操作模块';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.OPERATE_NAME IS '操作名';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.OPERATE_TYPE IS '操作分类';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.BEGIN_TIME IS '开始请求时间';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.END_TIME IS '结束请求时间';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.DURATION IS '执行时长(毫秒)';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.RESULT_CODE IS '结果码';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.RESULT_MSG IS '结果提示';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.CREATOR IS '创建者';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.UPDATER IS '更新者';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.DELETED IS '是否删除';
COMMENT ON COLUMN INFRA_API_ACCESS_LOG.TENANT_ID IS '租户编号';

-- ============================================================
-- 第3部分: INFRA_API_ERROR_LOG (API 异常日志表)
-- ============================================================

CREATE SEQUENCE INFRA_API_ERROR_LOG_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE INFRA_API_ERROR_LOG (
    ID BIGINT NOT NULL,
    TRACE_ID NVARCHAR2(64) NOT NULL,
    USER_ID BIGINT NOT NULL,
    USER_TYPE INTEGER NOT NULL,
    APPLICATION_NAME NVARCHAR2(50) NOT NULL,
    REQUEST_METHOD NVARCHAR2(16) NOT NULL,
    REQUEST_URL NVARCHAR2(255) NOT NULL,
    REQUEST_PARAMS NVARCHAR2(8000) NOT NULL,
    USER_IP NVARCHAR2(50) NOT NULL,
    USER_AGENT NVARCHAR2(512) NOT NULL,
    EXCEPTION_TIME TIMESTAMP(6) NOT NULL,
    EXCEPTION_NAME NVARCHAR2(128) NOT NULL,
    EXCEPTION_MESSAGE CLOB,
    EXCEPTION_ROOT_CAUSE_MESSAGE CLOB,
    EXCEPTION_STACK_TRACE CLOB,
    EXCEPTION_CLASS_NAME NVARCHAR2(512) NOT NULL,
    EXCEPTION_FILE_NAME NVARCHAR2(512) NOT NULL,
    EXCEPTION_METHOD_NAME NVARCHAR2(512) NOT NULL,
    EXCEPTION_LINE_NUMBER INTEGER NOT NULL,
    PROCESS_STATUS INTEGER NOT NULL,
    PROCESS_TIME TIMESTAMP(6),
    PROCESS_USER_ID BIGINT,
    CREATOR NVARCHAR2(64) DEFAULT '',
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    UPDATER NVARCHAR2(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP(6) NOT NULL,
    DELETED SMALLINT DEFAULT 0 NOT NULL,
    TENANT_ID BIGINT DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_INFRA_API_ERROR_LOG_TRACE_ID ON INFRA_API_ERROR_LOG(TRACE_ID);
CREATE INDEX IDX_INFRA_API_ERROR_LOG_USER_ID ON INFRA_API_ERROR_LOG(USER_ID);
CREATE INDEX IDX_INFRA_API_ERROR_LOG_CREATE_TIME ON INFRA_API_ERROR_LOG(CREATE_TIME);
CREATE INDEX IDX_INFRA_API_ERROR_LOG_PROCESS_STATUS ON INFRA_API_ERROR_LOG(PROCESS_STATUS);

COMMENT ON TABLE INFRA_API_ERROR_LOG IS 'API 异常日志表';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.ID IS '编号';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.TRACE_ID IS '链路追踪编号';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.USER_ID IS '用户编号';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.USER_TYPE IS '用户类型';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.APPLICATION_NAME IS '应用名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.REQUEST_METHOD IS '请求方法名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.REQUEST_URL IS '访问地址';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.REQUEST_PARAMS IS '请求参数';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.USER_IP IS '用户 IP';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.USER_AGENT IS '浏览器 UA';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_TIME IS '异常发生时间';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_NAME IS '异常名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_MESSAGE IS '异常消息';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_ROOT_CAUSE_MESSAGE IS '异常根因消息';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_STACK_TRACE IS '异常栈轨迹';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_CLASS_NAME IS '异常类全名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_FILE_NAME IS '异常文件名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_METHOD_NAME IS '异常方法名';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.EXCEPTION_LINE_NUMBER IS '异常行号';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.PROCESS_STATUS IS '处理状态';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.PROCESS_TIME IS '处理时间';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.PROCESS_USER_ID IS '处理用户编号';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.CREATOR IS '创建者';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.UPDATER IS '更新者';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.DELETED IS '是否删除';
COMMENT ON COLUMN INFRA_API_ERROR_LOG.TENANT_ID IS '租户编号';

-- ============================================================
-- 提交
-- ============================================================
COMMIT;
