import { CommandAdapt } from './CommandAdapt'

// 通过CommandAdapt中转避免直接暴露编辑器上下文
export class Command {
  public executeMode: CommandAdapt['config']
  public executeCut: CommandAdapt['config']
  public executeCopy: CommandAdapt['config']
  public executePaste: CommandAdapt['config']
  public executeSelectAll: CommandAdapt['config']
  public executeBackspace: CommandAdapt['config']
  public executeSetRange: CommandAdapt['config']
  public executeReplaceRange: CommandAdapt['config']
  public executeSetPositionContext: CommandAdapt['config']
  public executeForceUpdate: CommandAdapt['config']
  public executeBlur: CommandAdapt['config']
  public executeUndo: CommandAdapt['config']
  public executeRedo: CommandAdapt['config']
  public executePainter: CommandAdapt['config']
  public executeApplyPainterStyle: CommandAdapt['config']
  public executeFormat: CommandAdapt['config']
  public executeFont: CommandAdapt['config']
  public executeSize: CommandAdapt['config']
  public executeSizeAdd: CommandAdapt['config']
  public executeSizeMinus: CommandAdapt['config']
  public executeBold: CommandAdapt['config']
  public executeItalic: CommandAdapt['config']
  public executeUnderline: CommandAdapt['config']
  public executeStrikeout: CommandAdapt['config']
  public executeSuperscript: CommandAdapt['config']
  public executeSubscript: CommandAdapt['config']
  public executeColor: CommandAdapt['config']
  public executeHighlight: CommandAdapt['config']
  public executeTitle: CommandAdapt['config']
  public executeList: CommandAdapt['config']
  public executeRowFlex: CommandAdapt['config']
  public executeRowMargin: CommandAdapt['config']
  public executeInsertTable: CommandAdapt['config']
  public executeInsertTableTopRow: CommandAdapt['config']
  public executeInsertTableBottomRow: CommandAdapt['config']
  public executeInsertTableLeftCol: CommandAdapt['config']
  public executeInsertTableRightCol: CommandAdapt['config']
  public executeDeleteTableRow: CommandAdapt['config']
  public executeDeleteTableCol: CommandAdapt['config']
  public executeDeleteTable: CommandAdapt['config']
  public executeMergeTableCell: CommandAdapt['config']
  public executeCancelMergeTableCell: CommandAdapt['config']
  public executeSplitVerticalTableCell: CommandAdapt['config']
  public executeSplitHorizontalTableCell: CommandAdapt['config']
  public executeTableTdVerticalAlign: CommandAdapt['config']
  public executeTableBorderType: CommandAdapt['config']
  public executeTableBorderColor: CommandAdapt['config']
  public executeTableTdBorderType: CommandAdapt['config']
  public executeTableTdSlashType: CommandAdapt['config']
  public executeTableTdBackgroundColor: CommandAdapt['config']
  public executeTableSelectAll: CommandAdapt['config']
  public executeImage: CommandAdapt['config']
  public executeHyperlink: CommandAdapt['config']
  public executeDeleteHyperlink: CommandAdapt['config']
  public executeCancelHyperlink: CommandAdapt['config']
  public executeEditHyperlink: CommandAdapt['config']
  public executeSeparator: CommandAdapt['config']
  public executePageBreak: CommandAdapt['config']
  public executeAddWatermark: CommandAdapt['config']
  public executeDeleteWatermark: CommandAdapt['config']
  public executeSearch: CommandAdapt['config']
  public executeSearchNavigatePre: CommandAdapt['config']
  public executeSearchNavigateNext: CommandAdapt['config']
  public executeReplace: CommandAdapt['config']
  public executePrint: CommandAdapt['config']
  public executeReplaceImageElement: CommandAdapt['config']
  public executeSaveAsImageElement: CommandAdapt['config']
  public executeChangeImageDisplay: CommandAdapt['config']
  public executePageMode: CommandAdapt['config']
  public executePageScale: CommandAdapt['config']
  public executePageScaleRecovery: CommandAdapt['config']
  public executePageScaleMinus: CommandAdapt['config']
  public executePageScaleAdd: CommandAdapt['config']
  public executePaperSize: CommandAdapt['config']
  public executePaperDirection: CommandAdapt['config']
  public executeSetPaperMargin: CommandAdapt['config']
  public executeSetMainBadge: CommandAdapt['config']
  public executeSetAreaBadge: CommandAdapt['config']
  public executeInsertElementList: CommandAdapt['config']
  public executeInsertArea: CommandAdapt['config']
  public executeSetAreaValue: CommandAdapt['config']
  public executeSetAreaProperties: CommandAdapt['config']
  public executeLocationArea: CommandAdapt['config']
  public executeClearGraffiti: CommandAdapt['config']
  public executeAppendElementList: CommandAdapt['config']
  public executeUpdateElementById: CommandAdapt['config']
  public executeDeleteElementById: CommandAdapt['config']
  public executeSetValue: CommandAdapt['config']
  public executeRemoveControl: CommandAdapt['config']
  public executeTranslate: CommandAdapt['config']
  public executeSetLocale: CommandAdapt['config']
  public executeLocationCatalog: CommandAdapt['config']
  public executeWordTool: CommandAdapt['config']
  public executeSetHTML: CommandAdapt['config']
  public executeSetGroup: CommandAdapt['config']
  public executeDeleteGroup: CommandAdapt['config']
  public executeLocationGroup: CommandAdapt['config']
  public executeSetZone: CommandAdapt['config']
  public executeSetControlValue: CommandAdapt['config']
  public executeSetControlValueList: CommandAdapt['config']
  public executeSetControlExtension: CommandAdapt['config']
  public executeSetControlExtensionList: CommandAdapt['config']
  public executeSetControlProperties: CommandAdapt['config']
  public executeSetControlPropertiesList: CommandAdapt['config']
  public executeSetControlHighlight: CommandAdapt['config']
  public executeLocationControl: CommandAdapt['config']
  public executeInsertControl: CommandAdapt['config']
  public executeJumpControl: CommandAdapt['config']
  public executeUpdateOptions: CommandAdapt['config']
  public executeInsertTitle: CommandAdapt['config']
  public executeFocus: CommandAdapt['config']
  public getCatalog: CommandAdapt['config']
  public getImage: CommandAdapt['config']
  public getOptions: CommandAdapt['config']
  public getValue: CommandAdapt['config']
  public getValueAsync: CommandAdapt['config']
  public getAreaValue: CommandAdapt['config']
  public getHTML: CommandAdapt['config']
  public getText: CommandAdapt['config']
  public getWordCount: CommandAdapt['config']
  public getCursorPosition: CommandAdapt['config']
  public getRange: CommandAdapt['config']
  public getRangeText: CommandAdapt['config']
  public getRangeContext: CommandAdapt['config']
  public getRangeRow: CommandAdapt['config']
  public getRangeParagraph: CommandAdapt['config']
  public getKeywordRangeList: CommandAdapt['config']
  public getKeywordContext: CommandAdapt['config']
  public getPaperMargin: CommandAdapt['config']
  public getSearchNavigateInfo: CommandAdapt['config']
  public getLocale: CommandAdapt['config']
  public getGroupIds: CommandAdapt['config']
  public getControlValue: CommandAdapt['config']
  public getControlList: CommandAdapt['config']
  public getContainer: CommandAdapt['config']
  public getTitleValue: CommandAdapt['config']
  public getPositionContextByEvent: CommandAdapt['config']
  public getElementById: CommandAdapt['config']

  constructor(adapt: CommandAdapt) {
    // 全局命令
    this.executeMode = adapt.mode.bind(adapt)
    this.executeCut = adapt.cut.bind(adapt)
    this.executeCopy = adapt.copy.bind(adapt)
    this.executePaste = adapt.paste.bind(adapt)
    this.executeSelectAll = adapt.selectAll.bind(adapt)
    this.executeBackspace = adapt.backspace.bind(adapt)
    this.executeSetRange = adapt.setRange.bind(adapt)
    this.executeReplaceRange = adapt.replaceRange.bind(adapt)
    this.executeSetPositionContext = adapt.setPositionContext.bind(adapt)
    this.executeForceUpdate = adapt.forceUpdate.bind(adapt)
    this.executeBlur = adapt.blur.bind(adapt)
    // 撤销、重做、格式刷、清除格式
    this.executeUndo = adapt.undo.bind(adapt)
    this.executeRedo = adapt.redo.bind(adapt)
    this.executePainter = adapt.painter.bind(adapt)
    this.executeApplyPainterStyle = adapt.applyPainterStyle.bind(adapt)
    this.executeFormat = adapt.format.bind(adapt)
    // 字体、字体大小、字体变大、字体变小、加粗、斜体、下划线、删除线、字体颜色、背景色
    this.executeFont = adapt.font.bind(adapt)
    this.executeSize = adapt.size.bind(adapt)
    this.executeSizeAdd = adapt.sizeAdd.bind(adapt)
    this.executeSizeMinus = adapt.sizeMinus.bind(adapt)
    this.executeBold = adapt.bold.bind(adapt)
    this.executeItalic = adapt.italic.bind(adapt)
    this.executeUnderline = adapt.underline!.bind(adapt)
    this.executeStrikeout = adapt.strikeout.bind(adapt)
    this.executeSuperscript = adapt.superscript.bind(adapt)
    this.executeSubscript = adapt.subscript.bind(adapt)
    this.executeColor = adapt.color.bind(adapt)
    this.executeHighlight = adapt.highlight.bind(adapt)
    // 标题、对齐方式、列表
    this.executeTitle = adapt.title.bind(adapt)
    this.executeList = adapt.list.bind(adapt)
    this.executeRowFlex = adapt.rowFlex.bind(adapt)
    this.executeRowMargin = adapt.rowMargin.bind(adapt)
    // 表格、图片上传、超链接、搜索、打印、图片操作
    this.executeInsertTable = adapt.insertTable.bind(adapt)
    this.executeInsertTableTopRow = adapt.insertTableTopRow.bind(adapt)
    this.executeInsertTableBottomRow = adapt.insertTableBottomRow.bind(adapt)
    this.executeInsertTableLeftCol = adapt.insertTableLeftCol.bind(adapt)
    this.executeInsertTableRightCol = adapt.insertTableRightCol.bind(adapt)
    this.executeDeleteTableRow = adapt.deleteTableRow.bind(adapt)
    this.executeDeleteTableCol = adapt.deleteTableCol.bind(adapt)
    this.executeDeleteTable = adapt.deleteTable.bind(adapt)
    this.executeMergeTableCell = adapt.mergeTableCell.bind(adapt)
    this.executeCancelMergeTableCell = adapt.cancelMergeTableCell.bind(adapt)
    this.executeSplitVerticalTableCell =
      adapt.splitVerticalTableCell.bind(adapt)
    this.executeSplitHorizontalTableCell =
      adapt.splitHorizontalTableCell.bind(adapt)
    this.executeTableTdVerticalAlign = adapt.tableTdVerticalAlign.bind(adapt)
    this.executeTableBorderType = adapt.tableBorderType.bind(adapt)
    this.executeTableBorderColor = adapt.tableBorderColor.bind(adapt)
    this.executeTableTdBorderType = adapt.tableTdBorderType.bind(adapt)
    this.executeTableTdSlashType = adapt.tableTdSlashType.bind(adapt)
    this.executeTableTdBackgroundColor =
      adapt.tableTdBackgroundColor.bind(adapt)
    this.executeTableSelectAll = adapt.tableSelectAll.bind(adapt)
    this.executeImage = adapt.image.bind(adapt)
    this.executeHyperlink = adapt.hyperlink.bind(adapt)
    this.executeDeleteHyperlink = adapt.deleteHyperlink.bind(adapt)
    this.executeCancelHyperlink = adapt.cancelHyperlink.bind(adapt)
    this.executeEditHyperlink = adapt.editHyperlink.bind(adapt)
    this.executeSeparator = adapt.separator.bind(adapt)
    this.executePageBreak = adapt.pageBreak.bind(adapt)
    this.executeAddWatermark = adapt.addWatermark.bind(adapt)
    this.executeDeleteWatermark = adapt.deleteWatermark.bind(adapt)
    this.executeSearch = adapt.search.bind(adapt)
    this.executeSearchNavigatePre = adapt.searchNavigatePre.bind(adapt)
    this.executeSearchNavigateNext = adapt.searchNavigateNext.bind(adapt)
    this.executeReplace = adapt.replace.bind(adapt)
    this.executePrint = adapt.print.bind(adapt)
    this.executeReplaceImageElement = adapt.replaceImageElement.bind(adapt)
    this.executeSaveAsImageElement = adapt.saveAsImageElement.bind(adapt)
    this.executeChangeImageDisplay = adapt.changeImageDisplay.bind(adapt)
    // 页面模式、页面缩放、纸张大小、纸张方向、页边距
    this.executePageMode = adapt.pageMode.bind(adapt)
    this.executePageScale = adapt.pageScale.bind(adapt)
    this.executePageScaleRecovery = adapt.pageScaleRecovery.bind(adapt)
    this.executePageScaleMinus = adapt.pageScaleMinus.bind(adapt)
    this.executePageScaleAdd = adapt.pageScaleAdd.bind(adapt)
    this.executePaperSize = adapt.paperSize.bind(adapt)
    this.executePaperDirection = adapt.paperDirection.bind(adapt)
    this.executeSetPaperMargin = adapt.setPaperMargin.bind(adapt)
    // 签章
    this.executeSetMainBadge = adapt.setMainBadge.bind(adapt)
    this.executeSetAreaBadge = adapt.setAreaBadge.bind(adapt)
    // 区域
    this.getAreaValue = adapt.getAreaValue.bind(adapt)
    this.executeInsertArea = adapt.insertArea.bind(adapt)
    this.executeSetAreaValue = adapt.setAreaValue.bind(adapt)
    this.executeSetAreaProperties = adapt.setAreaProperties.bind(adapt)
    this.executeLocationArea = adapt.locationArea.bind(adapt)
    // 涂鸦
    this.executeClearGraffiti = adapt.clearGraffiti.bind(adapt)
    // 通用
    this.executeInsertElementList = adapt.insertElementList.bind(adapt)
    this.executeAppendElementList = adapt.appendElementList.bind(adapt)
    this.executeUpdateElementById = adapt.updateElementById.bind(adapt)
    this.executeDeleteElementById = adapt.deleteElementById.bind(adapt)
    this.executeSetValue = adapt.setValue.bind(adapt)
    this.executeRemoveControl = adapt.removeControl.bind(adapt)
    this.executeTranslate = adapt.translate.bind(adapt)
    this.executeSetLocale = adapt.setLocale.bind(adapt)
    this.executeLocationCatalog = adapt.locationCatalog.bind(adapt)
    this.executeWordTool = adapt.wordTool.bind(adapt)
    this.executeSetHTML = adapt.setHTML.bind(adapt)
    this.executeSetGroup = adapt.setGroup.bind(adapt)
    this.executeDeleteGroup = adapt.deleteGroup.bind(adapt)
    this.executeLocationGroup = adapt.locationGroup.bind(adapt)
    this.executeSetZone = adapt.setZone.bind(adapt)
    this.executeUpdateOptions = adapt.updateOptions.bind(adapt)
    this.executeInsertTitle = adapt.insertTitle.bind(adapt)
    this.executeFocus = adapt.focus.bind(adapt)
    // 获取
    this.getImage = adapt.getImage.bind(adapt)
    this.getOptions = adapt.getOptions.bind(adapt)
    this.getValue = adapt.getValue.bind(adapt)
    this.getValueAsync = adapt.getValueAsync.bind(adapt)
    this.getHTML = adapt.getHTML.bind(adapt)
    this.getText = adapt.getText.bind(adapt)
    this.getWordCount = adapt.getWordCount.bind(adapt)
    this.getCursorPosition = adapt.getCursorPosition.bind(adapt)
    this.getRange = adapt.getRange.bind(adapt)
    this.getRangeText = adapt.getRangeText.bind(adapt)
    this.getRangeContext = adapt.getRangeContext.bind(adapt)
    this.getRangeRow = adapt.getRangeRow.bind(adapt)
    this.getRangeParagraph = adapt.getRangeParagraph.bind(adapt)
    this.getKeywordRangeList = adapt.getKeywordRangeList.bind(adapt)
    this.getKeywordContext = adapt.getKeywordContext.bind(adapt)
    this.getCatalog = adapt.getCatalog.bind(adapt)
    this.getPaperMargin = adapt.getPaperMargin.bind(adapt)
    this.getSearchNavigateInfo = adapt.getSearchNavigateInfo.bind(adapt)
    this.getLocale = adapt.getLocale.bind(adapt)
    this.getGroupIds = adapt.getGroupIds.bind(adapt)
    this.getContainer = adapt.getContainer.bind(adapt)
    this.getTitleValue = adapt.getTitleValue.bind(adapt)
    this.getPositionContextByEvent = adapt.getPositionContextByEvent.bind(adapt)
    this.getElementById = adapt.getElementById.bind(adapt)
    // 控件
    this.executeSetControlValue = adapt.setControlValue.bind(adapt)
    this.executeSetControlValueList = adapt.setControlValueList.bind(adapt)
    this.executeSetControlExtension = adapt.setControlExtension.bind(adapt)
    this.executeSetControlExtensionList =
      adapt.setControlExtensionList.bind(adapt)
    this.executeSetControlProperties = adapt.setControlProperties.bind(adapt)
    this.executeSetControlPropertiesList =
      adapt.setControlPropertiesList.bind(adapt)
    this.executeSetControlHighlight = adapt.setControlHighlight.bind(adapt)
    this.getControlValue = adapt.getControlValue.bind(adapt)
    this.getControlList = adapt.getControlList.bind(adapt)
    this.executeLocationControl = adapt.locationControl.bind(adapt)
    this.executeInsertControl = adapt.insertControl.bind(adapt)
    this.executeJumpControl = adapt.jumpControl.bind(adapt)
  }
}
